# Generated by Django 3.2.5 on 2021-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='i_number',
            field=models.CharField(default=0, max_length=13),
        ),
    ]
