# Generated by Django 3.2.5 on 2021-07-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_i_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='i_number',
            new_name='id_number',
        ),
    ]
