# Generated by Django 3.2.5 on 2021-07-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_rename_i_number_lead_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Female')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='physical_address',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='postal_address',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
