# Generated by Django 3.2.5 on 2021-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210722_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('bank_statement', models.FileField(upload_to='supporting_docs/bank_statement/')),
                ('id_copy', models.FileField(upload_to='supporting_docs/id_copy/')),
                ('proof_residence', models.FileField(upload_to='supporting_docs/proof_residence/')),
                ('water_proof', models.FileField(upload_to='supporting_docs/water_proof/')),
                ('electricity_proof', models.FileField(upload_to='supporting_docs/electricty_proof/')),
                ('sworn_affidavit', models.FileField(upload_to='supporting_docs/sworn_affidavit/')),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30),
        ),
    ]
